config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comics

  root 'comics#index'


  
end

app/models/comic.rb
class Comic < ActiveRecord::Base
  belongs_to :user

  has_attached_file :image, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  before_action :set_comic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @comics = Comic.all
  end


  def show
  end


  def new
    # this is good!
    @comic = current_user.comics.build
  end


  def edit
  end


  def create
    @comic = current_user.comics.build(comic_params)

    # I'd remove this until you actually have a use for your app to be an API
    # I'd also suggest against using scaffold generator until you've built ~4
    # rails apps by hand
    respond_to do |format|
      if @comic.save
        format.html { redirect_to @comic, notice: 'Comic was successfully created.' }
        format.json { render :show, status: :created, location: @comic }
      else
        format.html { render :new }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @comic.update(comic_params)
        format.html { redirect_to @comic, notice: 'Comic was successfully updated.' }
        format.json { render :show, status: :ok, location: @comic }
      else
        format.html { render :edit }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @comic.destroy
    respond_to do |format|
      format.html { redirect_to comics_url, notice: 'Comic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_comic
      @comic = Comic.find(params[:id])
    end


    def comic_params
      params.require(:comic).permit(:title, :desrciption, :photo_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/views/comics/_form.html.erb
<%= form_for @comic, html: { multipart: true } do |f| %>
  <% if @comic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comic.errors.count, "error") %> prohibited this comic from being saved:</h2>

      <ul>
      <% @comic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :desrciption %><br>
    <%= f.text_area :desrciption %>
  </div>
  <div class="field">
    <%= f.label :photo_url %><br>
    <%= f.text_field :photo_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comics/edit.html.erb
<h1>Editing Comic</h1>

<%= render 'form' %>

<%= link_to 'Show', @comic %> |
<%= link_to 'Back', comics_path %>

app/views/comics/index.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>The Best Comics Reviewed Here</h1>
      <p>Keep up on the latest, greatest, and most exciting comics in the industry! Know what issues pack a punch or what issues
      are just plain old filler. This is The Comic Corner. </p>
      <p><%= link_to "Dare to be Awesome", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>


<div class="row">
  <% @comics.each do |comic| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag comic.photo_url, class: 'photo_url'), comic %>
      </div>
    </div>
  <% end %>
</div>

app/views/comics/new.html.erb
<h1>New Comic</h1>

<%= render 'form' %>

<%= link_to 'Back', comics_path %>

app/views/comics/show.html.erb
<!-- This is a LOT of nested divs... I'd generally suggest against having this
many for such a small amount of content. Additionally, a table is not the best
element for layout here. Tables should only be used for tabular data, not layout.
Semantic HTML5 elements like main, section, etc would be better -->
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @comic.photo_url, class: 'photo_url' %>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Title:</strong></td>
                <td><%= @comic.title %></td>
              </tr>
              <tr>
                <strong>Desrciption:</strong>
                <%= @comic.desrciption %>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_comic_path(@comic) %> |
<%= link_to 'Back', comics_path %>
<%= link_to 'Delete', comic_path(@comic), method: :delete %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <!--
              what are all these extra spans doing? This feels like layout code that you copy/pasted modified
              which is not bad, except if you do so, you need to make sure you're adapting the code correctly to your
              needs
         -->
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to " The Comic Corner", root_path, class: "navbar-brand" %>
    </div>


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "New Comic", new_comic_path, class: "active" %></li>
          <li><%= link_to "Account", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ComicReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- nice use of a partial for the header -->
  <%= render 'layouts/header' %>
  <% flash.each do |name, msg| %>
    <% content_tag(:div, msg, class: "alert alert-info") %>
    <% end %> <!-- this should be indented two spaces to the left -->
    <%= yield %>

</body>
</html>